apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers: 
      - name: gcp-devops-gke
        image: gcr.io/noble-truck-388707/gcpdevops@sha256:51e285790a3551e8f0ac5fdea6ce1b24b6bb00fbcfab478426dd03f64d921f4e
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"        
