apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gcp-devops-gke
spec:
  template:
     metadata:
      labels:
        app: gcp
     spec:
      containers:
      - name: gke-deploy
        image: gcr.io/$PROJECT_ID/gcp-devops
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
  replicas: 1
  selector: 
    matchLabels:
        app: gcp
      

